#EXAMPLE DB SEEDING
CREATE DATABASE gamestore;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE games(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  imageurl TEXT NOT NULL,
  categories TEXT[],
  price REAL NOT NULL
);